---
meta:
  name:    cf-pancake
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  initial_version: 0.2.0

  go:
    version: "1.12"
    binary: cf-pancake
    cmd_module: .

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-2
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   cf-pancake
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       UNKNOWN
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#cf-pancake"
